export const DEFAULT_PRIMARY_COLOR = '#000000',
    DEFAULT_SECONDARY_COLOR = '#FF0000',
    INITIAL_COUNTER = 0,
    DEFAULT_FPS = 12,
    ERASER_COLOR = '#FFF',
    SECONDARY_BUTTON = 2,
    CANVAS_DIMENSION = '2d',
    EXPORT_FILE_NAME = 'animation.gif'